### ISSUE TITLE
Pyvsc plugin issue (not a pip issue)

### ISSUE THREAD

**Issue by vidushiy25** [openhwgroup/core-v-verif#2273]
![Screenshot 2023-11-01 at 22 04 55](https://github.com/openhwgroup/core-v-verif/assets/91960705/48bf3ca6-46e0-44ad-8d20-2e1acb405863)

Hi I am trying to install the python plugins for simulation purposes. However I get this error: 

`Discarding https://files.pythonhosted.org/packages/94/01/6a7c8b476eefdabdeeaac30bf9227c55d6ccb0638b2573a3fe3ebff1bc4f/PyBoolector-3.2.2.20230911.3.tar.gz (from https://pypi.org/simple/pyboolector/): Requested pyboolector>=3.2.2 from https://files.pythonhosted.org/packages/94/01/6a7c8b476eefdabdeeaac30bf9227c55d6ccb0638b2573a3fe3ebff1bc4f/PyBoolector-3.2.2.20230911.3.tar.gz (from pyvsc==0.6.3.1400856349) has inconsistent version: expected '3.2.2.20230911.3', but metadata has '3.2.2'
  Using cached PyBoolector-3.2.2.20230110.4.tar.gz (21 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/private/var/folders/88/jd11r8_n6hb0105bp_lw_by80000gn/T/pip-build-env-2bcw4o8y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/private/var/folders/88/jd11r8_n6hb0105bp_lw_by80000gn/T/pip-build-env-2bcw4o8y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/private/var/folders/88/jd11r8_n6hb0105bp_lw_by80000gn/T/pip-build-env-2bcw4o8y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/private/var/folders/88/jd11r8_n6hb0105bp_lw_by80000gn/T/pip-build-env-2bcw4o8y/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 14, in <module>
      FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/88/jd11r8_n6hb0105bp_lw_by80000gn/T/pip-install-wzcz0gma/CMakeLists.txt'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

**Comment by MikeOpenHWGroup** [comment]
Hi @vidushiy25, thanks for your interest in OpenHW and CORE-V-VERIF. As I stated in #2271, we are not in a position to help people with issues related to your local computer installation.
